### PR TITLE
Added copy constructor and test case for min heap

### PR DESCRIPTION
**Pull request by Xoulios**
I think the add copy constructors to all classes issue can be closed now

### CODE REVIEW

**Comment by spirosmaggioros** [comment]
I think there's a library missing for INT_MAX/INT_MIN cause the build is failing.
Good thing that we have automatic test running now, in every push to this branch test cases will run automatically and have to pass. I think it's a minor error, you can see in the build process what failed in details

**Comment by Xoulios** [comment]
I think the issues are resolved now

**Comment by Xoulios** [comment]
I do not know what keeps failing. Everything seems to be alright on my machine.

**Comment by spirosmaggioros** [comment]
Can you add some if statements and maybe some more checks for the code? 
It seems that the coverage dropped 0.12%, so see if you can do something about it otherwise i will look at it

**Comment by spirosmaggioros** [comment]
This will be closed due to inactivity and a lot of conflicts

**Pull request closed without merging**
