### PR TITLE
Add interpolation search and ternary search algorithms and tests

### PR DESCRIPTION
**Pull request by Shu-AFK**
Added a new file for the interpolation search algorithm, as well as the ternary search algorithm, including its implementations and tests. Also, added `cstdint` library to the counting_sort.h.

### CODE REVIEW

**Comment by Shu-AFK** [comment]
It's fixed now

**Comment by spirosmaggioros** [comment]
Floyd, it still has segmentation faults. Just remake it to work without RandomIterators because i don't really know how the substractions are done in the process. Are the test cases ok for your OS?

**Comment by Shu-AFK** [comment]
The test cases compiled and ran fine for me yesterday

**Comment by Shu-AFK** [comment]
I can't really test it because it worked for me before but test it, it might be fixed now

**Comment by spirosmaggioros** [comment]
Now all test cases pass!

**Pull request merged**
